version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: cnl_admin
      POSTGRES_PASSWORD: cnl_admin_dr_to
      POSTGRES_DB: cnl_file_management_db
    ports:
      - "5465:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

volumes:
  postgres_dev_data:
