version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: cnl_admin
      POSTGRES_PASSWORD: cnl_admin_dr_to
      POSTGRES_DB: cnl_file_management_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://cnl_admin:cnl_admin_dr_to@db:5432/cnl_file_management_db
      - ADMIN_EMAIL=admin
      - ADMIN_PASSWORD=admindrto
    depends_on:
      - db

volumes:
  postgres_dev_data:
