export const PERMISSIONS = {
  DASHBOARD_VIEW: "DASHBOARD_VIEW",

  FILES_VIEW: "FILES_VIEW",
  FILES_UPDATE: "FILES_UPDATE",
  FILES_UPLOAD: "FILES_UPLOAD",
  FILES_DELETE: "FILES_DELETE",

  FOLDERS_VIEW: "FOLDERS_VIEW",
  FOLDERS_CREATE: "FOLDERS_CREATE",
  FOLDERS_UPDATE: "FOLDERS_UPDATE",
  FOLDERS_DELETE: "FOLDERS_DELETE",

  FILTERS_VIEW: "FILTERS_VIEW",
  FILTERS_CREATE: "FILTERS_CREATE",
  FILTERS_UPDATE: "FILTERS_UPDATE",
  FILTERS_DELETE: "FILTERS_DELETE",

  GROUPS_VIEW: "GROUPS_VIEW",
  GROUPS_CREATE: "GROUPS_CREATE",
  GROUPS_UPDATE: "GROUPS_UPDATE",
  GROUPS_DELETE: "GROUPS_DELETE",

  ROLES_VIEW: "ROLES_VIEW",
  ROLES_CREATE: "ROLES_CREATE",
  ROLES_UPDATE: "ROLES_UPDATE",
  ROLES_DELETE: "ROLES_DELETE",

  USERS_VIEW: "USERS_VIEW",
  USERS_CREATE: "USERS_CREATE",
  USERS_UPDATE: "USERS_UPDATE",
  USERS_DELETE: "USERS_DELETE",

  SUPER_ADMIN: "*",
} as const;

export type Permission = keyof typeof PERMISSIONS;
export type PermissionValue = (typeof PERMISSIONS)[Permission];

export const PERMISSION_GROUPS = {
  dashboard: [PERMISSIONS.DASHBOARD_VIEW],
  files: [
    PERMISSIONS.FILES_VIEW,
    PERMISSIONS.FILES_UPDATE,
    PERMISSIONS.FILES_UPLOAD,
    PERMISSIONS.FILES_DELETE,
  ],
  folders: [
    PERMISSIONS.FOLDERS_VIEW,
    PERMISSIONS.FOLDERS_CREATE,
    PERMISSIONS.FOLDERS_UPDATE,
    PERMISSIONS.FOLDERS_DELETE,
  ],
  filters: [
    PERMISSIONS.FILTERS_VIEW,
    PERMISSIONS.FILTERS_CREATE,
    PERMISSIONS.FILTERS_UPDATE,
    PERMISSIONS.FILTERS_DELETE,
  ],
  // groups: [
  //   PERMISSIONS.GROUPS_VIEW,
  //   PERMISSIONS.GROUPS_CREATE,
  //   PERMISSIONS.GROUPS_UPDATE,
  //   PERMISSIONS.GROUPS_DELETE,
  // ],
  roles: [
    PERMISSIONS.ROLES_VIEW,
    PERMISSIONS.ROLES_CREATE,
    PERMISSIONS.ROLES_UPDATE,
    PERMISSIONS.ROLES_DELETE,
  ],
  users: [
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_UPDATE,
    PERMISSIONS.USERS_DELETE,
  ],
};

export const PERMISSION_DEPENDENCIES: Record<string, string[]> = {
  //FILES_DEPENDENCIES
  [PERMISSIONS.FILES_VIEW]: [PERMISSIONS.FILTERS_VIEW],
  [PERMISSIONS.FILES_UPDATE]: [
    PERMISSIONS.FILES_VIEW,
    PERMISSIONS.FILTERS_VIEW,
  ],
  [PERMISSIONS.FILES_UPLOAD]: [PERMISSIONS.FILES_VIEW],
  [PERMISSIONS.FILES_DELETE]: [PERMISSIONS.FILES_VIEW],
  //FOLDERS_DEPENDENCIES
  [PERMISSIONS.FOLDERS_CREATE]: [PERMISSIONS.FOLDERS_VIEW],
  [PERMISSIONS.FOLDERS_UPDATE]: [PERMISSIONS.FOLDERS_VIEW],
  [PERMISSIONS.FOLDERS_DELETE]: [PERMISSIONS.FOLDERS_VIEW],
  //FILTERS_DEPENDENCIES
  [PERMISSIONS.FILTERS_CREATE]: [PERMISSIONS.FILTERS_VIEW],
  [PERMISSIONS.FILTERS_UPDATE]: [PERMISSIONS.FILTERS_VIEW],
  [PERMISSIONS.FILTERS_DELETE]: [PERMISSIONS.FILTERS_VIEW],
  //ROLES_DEPENDENCIES
  [PERMISSIONS.ROLES_CREATE]: [PERMISSIONS.ROLES_VIEW],
  [PERMISSIONS.ROLES_UPDATE]: [PERMISSIONS.ROLES_VIEW],
  [PERMISSIONS.ROLES_DELETE]: [PERMISSIONS.ROLES_VIEW],
  //USERS_DEPENDENCIES
  [PERMISSIONS.USERS_CREATE]: [PERMISSIONS.USERS_VIEW, PERMISSIONS.ROLES_VIEW],
  [PERMISSIONS.USERS_UPDATE]: [PERMISSIONS.USERS_VIEW],
  [PERMISSIONS.USERS_DELETE]: [PERMISSIONS.USERS_VIEW],
};
