// lib/constants/permissions.ts

export const PERMISSIONS = {
  // Dashboard
  DASHBOARD_VIEW: "DASHBOARD_VIEW",

  // Files
  FILES_VIEW: "FILES_VIEW",
  FILES_UPLOAD: "FILES_UPLOAD",
  FILES_MANAGE: "FILES_MANAGE",

  // Folders
  FOLDERS_VIEW: "FOLDERS_VIEW",
  FOLDERS_MANAGE: "FOLDERS_MANAGE",

  // Filters / Metadata
  FILTERS_VIEW: "FILTERS_VIEW",
  FILTERS_MANAGE: "FILTERS_MANAGE",

  // Comments
  COMMENTS_VIEW: "COMMENTS_VIEW",
  COMMENTS_MANAGE: "COMMENTS_MANAGE",

  // Roles & Permissions
  ROLES_VIEW: "ROLES_VIEW",
  ROLES_MANAGE: "ROLES_MANAGE",

  // Users
  USERS_VIEW: "USERS_VIEW",
  USERS_MANAGE: "USERS_MANAGE",


  // Wildcard
  SUPER_ADMIN: "*",
} as const;

export type Permission = keyof typeof PERMISSIONS;
export type PermissionValue = (typeof PERMISSIONS)[Permission];

export const PERMISSION_GROUPS = {
  files: [PERMISSIONS.FILES_VIEW, PERMISSIONS.FILES_MANAGE],
  folders: [PERMISSIONS.FOLDERS_VIEW, PERMISSIONS.FOLDERS_MANAGE],
  filters: [PERMISSIONS.FILTERS_VIEW, PERMISSIONS.FILTERS_MANAGE],
  comments: [PERMISSIONS.COMMENTS_VIEW, PERMISSIONS.COMMENTS_MANAGE],
  roles: [PERMISSIONS.ROLES_VIEW, PERMISSIONS.ROLES_MANAGE],
  users: [PERMISSIONS.USERS_VIEW, PERMISSIONS.USERS_MANAGE],
};
